name: Build HsMod

on:
  push:
    branches: [ "bepinex5" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v1.3

      - name: Restore NuGet
        run: nuget restore HsMod.sln

      - name: Build
        run: msbuild HsMod.sln /p:Configuration=Release

      - name: List files after build
        run: |
          echo "===== ROOT ====="
          dir
          echo "===== HsMod ====="
          dir HsMod
          echo "===== BIN ====="
          dir HsMod\bin
          echo "===== RELEASE ====="
          dir HsMod\bin\Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HsMod-build
          path: |
            **/*.dll
